{% set version = '0.1.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fateid
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/FateID_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FateID/FateID_{{ version }}.tar.gz
    - https://depot.galaxyproject.org/software/r-fateid/r-fateid_{{ version }}_src_all.tar.gz
  sha256: 4d2dc706b88b9545ee1aa414182e4eba7f73a4db818fd92476e5b260f3871723

build:
  merge_build_host: True  # [win]

  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcolorbrewer
    - r-rtsne
    - r-lle
    - r-locfit
    - r-pheatmap
    - r-princurve
    - r-randomforest
    - r-rgl
    - r-som

  run:
    - r-base
    - r-rcolorbrewer
    - r-rtsne
    - r-lle
    - r-locfit
    - r-pheatmap
    - r-princurve
    - r-randomforest
    - r-rgl
    - r-som

test:
  commands:

    - $R -e "library('FateID')"           # [not win]
    - "\"%R%\" -e \"library('FateID')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=FateID
  license: GPL-3
  summary: "Application of 'FateID' allows computation and visualization of cell fate bias for
    multi-lineage single cell transcriptome data. Herman, J.S., Sagar, Gr\xFCn D. (2017)
    <DOI:10.1038/nmeth.4662>."

  license_family: GPL3
extra:
  identifiers:
    - doi:10.1038/nmeth.4662
  container:
    # needed for libGL.so.1
    extended-base: true
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
